coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 0%
        flags:
          - unit
        paths:
          - "src"
        # advanced settings
        if_ci_failed: success #success, failure, error, ignore
        informational: false
        only_pulls: false
    patch: false

comment:                  # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]

# 참고 : https://docs.codecov.com/docs/pull-request-comments
