server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080

spring:
  profiles:
    default: h2

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      # default : 1MB
      maxFileSize: 30MB
      maxRequestSize: 30MB

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

cloud:
  aws:
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY}
      secretKey: ${AWS_S3_SECRET_KEY}
    cloudfront:
      url: ${AWS_CLOUDFRONT_URL}
    s3:
      bucket: devnity-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  header: Authorization
  issuer: ${JWT_ISSUER}
  client-secret: ${JWT_SECRET}
  expiry-seconds: 36000

cors:
  origins:
    - "*"

slack:
  webhookUrl: ${SLACK_WEBHOOK_URL_DEV}
  redirectUrl: "http://team7-devnity-front-dev.s3-website.ap-northeast-2.amazonaws.com"
