spring:
  datasource:
    url: ${DB_URL_PROD}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: never

cors:
  origins:
    - "https://devnity.xyz"

slack:
  webhookUrl: ${SLACK_URL_ALARM_PROD}
  redirectUrl: "https://devnity.xyz"
