spring:
  datasource:
    url: ${DB_URL_DEV}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: never

cors:
  origins:
    - "http://localhost:8000"
    - "http://team7-devnity-front-dev.s3-website.ap-northeast-2.amazonaws.com"
