spring:
  datasource:
    url: ${DB_URL_PROD}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create  # FIXME : 나중에 최종 배포 전에만 한번 쓰고 validate로 바꿔야함 !!!!!!!