spring:
  datasource:
    url: ${DB_URL_PROD}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create  # FIXME : 최종 배포 전 최초 1회만 create, 이후 validate로 변경
    defer-datasource-initialization: true

  sql:
    init:
      mode: always   # FIXME : 배포 후 never로 변경

cors:
  origins:
    - "https://devnity.xyz"

slack:
  webhookUrl: ${SLACK_WEBHOOK_URL_PROD}
  redirectUrl: "https://devnity.xyz"
